version: '3.8'

networks:
  base:

services:
  # 1. lotus编译环境
  filecoin-blotus:
    image: ${IMAGE_BLOTUS}
    container_name: ${CONTAINER_BLOTUS}
    stdin_open: true
    tty: true
    environment:
      - CGO_CFLAGS_ALLOW="-D__BLST_PORTABLE__"
      - CGO_CFLAGS="-D__BLST_PORTABLE__"
    privileged: true
    entrypoint: ["sh"]
    volumes:
      - $ROOT_PATH/data-server/${CONTAINER_BLOTUS}/lotus:/go/src/github.com/filecoin-project/lotus
    networks:
      base:

  # 2. lotus运行环境
  filecoin-elotus:
    image: ${IMAGE_ELOTUS}
    container_name: ${CONTAINER_ELOTUS}
    stdin_open: true
    tty: true
    privileged: true
    entrypoint: ["sh"]
    environment:
      # #   这两个环境变量是在测试环境下编译时，针对amd和旧intel的配置
      - LOTUS_PATH=~/.lotusDevnet
      - LOTUS_MINER_PATH=~/.lotusminerDevnet
    volumes:
      - $ROOT_PATH/data-server/${CONTAINER_ELOTUS}/bin:/lotus/bin/
      - $ROOT_PATH/data-server/${CONTAINER_ELOTUS}/tmp:/var/tmp/
      - $ROOT_PATH/data-server/${CONTAINER_ELOTUS}/lotusminerDevnet:/data/lotusminerDevnet
      - $ROOT_PATH/data-server/${CONTAINER_ELOTUS}/lotusDevnet:/data/lotusDevnet
      - $ROOT_PATH/data-server/${CONTAINER_ELOTUS}/genesis-sectors:/root/.genesis-sectors/
    ports:
      - 1234:1234
      - 1235:1235
    networks:
      base:
