version: '3.8'

networks:
  base:

services:
  # 1. lotus编译环境
  filecoin-blotus:
    image: ${IMAGE_BLOTUS}
    container_name: ${CONTAINER_BLOTUS}
    stdin_open: true
    tty: true
    privileged: true
    entrypoint: ["sh"]
    volumes:
      - $ROOT_PATH/data-server/${CONTAINER_BLOTUS}/lotus:/go/src/github.com/filecoin-project/lotus
    networks:
      base:
